MQTT_SERVER = "mqtt.ohstem.vn"
MQTT_PORT = 1883
MQTT_USERNAME = "nguyentruongthan"
MQTT_PASSWORD = ""

USERNAME = "hoangs369"


HEADER_GATEWAY_ACK = 0

HEADER_GATEWAY_REQUEST_GET_COWS = 1
HEADER_BACKEND_RESPONSE_GET_COWS = 2

HEADER_BACKEND_CREATE_COW = 3
HEADER_BACKEND_DELETE_COW = 4
HEADER_BACKEND_UPDATE_COW = 5

HEADER_GATEWAY_SEND_COW_GPS_AND_STATUS = 6

HEADER_GATEWAY_REQUEST_GROUPS = 7
HEADER_BACKEND_RESPONSE_GROUPS = 8

HEADER_GATEWAY_SEND_ERROR = 9

HEADER_GATEWAY_SEND_COW_STATUS = 10

HEADER_BACKEND_CREATE_GROUP = 11
HEADER_BACKEND_DELETE_GROUP = 12
HEADER_BACKEND_UPDATE_GROUP = 13

COW_NOT_RESPONSE = 0